add contact page and navigation for this page
arix2000/LibraryWebApplication pull request #18
Opened 2023-05-06 21:46 UTC by maciekkielducki

oszczedzcie mnie XD

2023-05-07 10:32 UTC, arix2000 commented
Brakuje skalowalności:
![Screenshot from 2023-05-07 12-29-34](https://user-images.githubusercontent.com/39887315/236672279-ac5d0112-5b5b-4a1e-8fb7-416f224a18aa.png)
![Screenshot from 2023-05-07 12-29-46](https://user-images.githubusercontent.com/39887315/236672294-37a2d820-4a14-494a-939b-0edfe406dedc.png)

2023-05-07 10:32 UTC, arix2000 requested changes
Overall nie tak źle :t-rex: :partying_face:

2023-05-07 10:32 UTC, arix2000 commented on src/components/ContactPage/ContactPage.js
> +            {people.map((person) => (
Dobrze by było mieć UI elementu listy w osobnym pliku

2023-05-08 18:38 UTC, joohnnyvv commented on src/components/ContactPage/ContactPage.js
> +            {people.map((person) => (
Facts

2023-05-08 18:40 UTC, joohnnyvv commented on src/components/ContactPage/ContactPage.js
> +                            <p>Linkedin:
Literówka - możesz poprawić na LinkedIn

2023-05-08 18:40 UTC, joohnnyvv commented on src/components/ContactPage/ContactPage.js
> +                            <p>Github:
Tutaj też daj GitHub

2023-05-08 18:52 UTC, joohnnyvv commented on src/components/ContactPage/ContactPage.js
> +                            <p>Email: {person.email}</p>
Dałbym klikalny email żeby po kliknięciu przenosiło do domyślnej apki poczty, tu masz przykład:
<a href = "mailto: abc@example.com">Send Email</a>

Musisz zacząć href od "mailto:" :)

2023-05-08 18:52 UTC, joohnnyvv commented on src/components/ContactPage/ContactPage.js
> +                            <p>Phone: {person.phone}</p>
Tutaj tak jak z mailem dałbym klikalny numer telefonu, tu masz przykład:
<a href="tel:+48123-456-789">Call Me Maybe</a>

2023-05-08 18:56 UTC, joohnnyvv requested changes
Ogólnie spoko ale rzeczywiście dobrze jakbyś stworzył osobny komponent i mapował do niego osoby z listy :)
No i możesz spróbować zastosować się do moich sugestii 👯‍♀️

2023-07-01 13:47 UTC, joohnnyvv approved these changes
Cieszę się, że udało się przebrnąć przez tego taska :')

2023-07-01 15:03 UTC, arix2000 commented
![Screenshot from 2023-07-01 15-57-51](https://github.com/arix2000/LibraryWebApplication/assets/39887315/b58eef78-175e-4097-bf9e-74a6223133b5)
problem z responsywnością, wystarczy zmienić moment tej przemiany na mobilny widok żeby odpalał się nieco wcześniej

2023-07-01 15:07 UTC, arix2000 requested changes, later dismissed
Małe poprawki + konflikty ogarnij

2023-07-01 15:07 UTC, arix2000 commented on src/components/ContactPage/ContactPage.js
> +                borderRadius: '2rem',
nie używaj rem i em do określania wielkości innch niż czcionka, Więcej info: https://clivio.pl/roznica-miedzy-jednostkami-em-i-rem-w-css/

2023-07-01 15:07 UTC, arix2000 commented on src/components/ContactPage/ContactPage.js
> +                    borderRadius: '2rem',
to samo co wyżej

2023-07-03 23:27 UTC, merged