Lib 10 home page
arix2000/LibraryWebApplication pull request #21
Opened 2023-06-02 09:08 UTC by joohnnyvv

Voilà, messieurs les députés

2023-06-05 18:14 UTC, arix2000 requested changes

2023-06-05 18:14 UTC, arix2000 commented on src/common/UserBookManager.js
> +    return user.borrowed_books.includes(bookId);
Cofnij tą zmiane najlepiej zrobiłem refactor całego tego pliku w history book, lepiej unikać konfliktów

2023-06-05 18:14 UTC, arix2000 commented on src/components/BookSearch/common/BorrowButton.js
> +        {isBookReserved ? "Cancel Res." : "Reserve"}{" "}
to "Cancel Res." trzeba zamienić już jakoś sensowniej, tylko pewnie w css będzie trzeba zrobić żeby ucinało to co się nie zmieści

2023-06-05 18:14 UTC, arix2000 commented on src/components/HomePage/HomePage.js
> +          border={border}
pole `border` nie jest zdefiniowane w `HomePageBanner` -> nie jest tam nigdy wykorzystywane

2023-06-05 18:14 UTC, arix2000 commented on src/components/HomePage/HomePage.js
> +            showSearchBar={false}
pole `showSearchBar` nie jest wykorzysytywane ani zdefiniowane w `Banner`, tak samo jest przy każdym innym wywołaniu w tym pliku.

2023-06-05 18:14 UTC, arix2000 commented on src/components/HomePage/HomePageBanner.js
> +  showSearchBar,
`showSearchBar` jest wykorzystywane ale nigdzie nie przypisywane, czyli zawsze będzie null albo false (zależy jak to tam js przypisuje)

2023-06-05 18:14 UTC, arix2000 commented on src/components/UiCommon/NavBar.jsx
Widze że odkryłeś `Option+shift+F` XD, Na ogół nie rób takich rzeczy w pliku którego nie zmieniałeś, 
1. Utrudnia to Crke bo trzeba przepatrzeć kod który w rzeczywistości się nie zmienił
2. Może to dosyć potężnie się odgryźć w Confliktach, tobie albo innym.
Lepiej to zrobić jako osobny task na całym projekcie, pare kliknięć i cały projekt będzie przeformatowany bez zbędnych konfliktów (zakładając że wszystkie zadania będą już skończone)

2023-06-05 18:14 UTC, arix2000 commented on src/components/styles/homePage/homePage.module.css
> +  padding-bottom: 1rem;
Nie używaj `rem` i `em` do określania czekogolwiek innego niż wielkości czcionek, jest to jednostka relatywna do pierwszej stałej jednostki napisów w drzewie, oznacza to tyle że gdybyś chciał zmienić defaultową wielkość czcionki na całym screenie albo w całej w apce to to spowoduje że ci się zaczną paddingi, marginy gdziekolwiek indziej tego użyłeś rozjeżdżać.

2023-06-05 18:14 UTC, arix2000 commented on src/components/styles/homePage/homePage.module.css
> +  margin-right: 1rem;
tak jak powyżej

2023-06-05 18:14 UTC, arix2000 commented on src/components/styles/navBar.module.css
To samo co tutaj napisałem: https://github.com/arix2000/LibraryWebApplication/pull/21/files#r1218416649
+ Jak coś to nie musisz teraz tego cofać wszystkiego, tylko pamiętaj na przyszłość :P

2023-06-05 18:14 UTC, arix2000 commented on src/components/styles/navBar.module.css
To samo co tutaj napisałem: https://github.com/arix2000/LibraryWebApplication/pull/21/files#r1218416649
Jak coś to nie musisz teraz tego cofać wszystkiego, tylko pamiętaj na przyszłość :P

2023-06-06 09:32 UTC, arix2000 commented
Zmień wysokość tych banerów żeby nie można było ich scrollować wertykalnie i żeby cały item na wysokość się mieścił: 
![image](https://github.com/arix2000/LibraryWebApplication/assets/39887315/43fee108-2994-4f5c-b285-058d729c8155)

2023-06-06 09:35 UTC, arix2000 commented
Zrób stałą wysokość dla całego page'a żeby nie wywalało scrolla do góry przy rezerwowaniu, pożyczaniu itp.

2023-06-06 09:37 UTC, arix2000 commented
Te banery kiedy są puste nie pasują do reszty apki, apka ma ciemny motyw, więc kolory tutaj też powinny być ciemne (napewno w background) żeby pasowały do reszty.
![image](https://github.com/arix2000/LibraryWebApplication/assets/39887315/1e29b50f-6406-4d00-8cf6-41c6846401a4)

2023-06-06 09:41 UTC, arix2000 commented
Zmieńmy tekst na `Search for books` albo `Search for available books` jako że to nie są nasze książki tylko książki które wypożyczamy.

![image](https://github.com/arix2000/LibraryWebApplication/assets/39887315/ca1650ec-c951-4ee8-8e95-bfbb8f7daf8d)

2023-06-06 09:42 UTC, joohnnyvv commented on src/components/UiCommon/NavBar.jsx
Czasami zapominam co zmieniałem :((

2023-06-06 09:46 UTC, joohnnyvv commented on src/components/styles/homePage/homePage.module.css
> +  margin-right: 1rem;
To nie ja pisałem te klasy.... chyba

2023-06-06 09:46 UTC, joohnnyvv commented on src/components/styles/homePage/homePage.module.css
> +  margin-right: 1rem;
Może po formatowaniu tak wyszło :(

2023-06-06 11:44 UTC, arix2000 approved these changes
Nice! :sunglasses:

2023-06-06 11:49 UTC, merged