Lib 16 book history
arix2000/LibraryWebApplication pull request #22
Opened 2023-06-06 12:27 UTC by arix2000

https://www.youtube.com/watch?v=dQw4w9WgXcQ

2023-06-06 23:22 UTC, joohnnyvv commented
Kod ładny imo, daje okejke

2023-06-06 23:30 UTC, joohnnyvv commented
<img width="1680" alt="image" src="https://github.com/arix2000/LibraryWebApplication/assets/110868938/3772fde8-222e-445d-887f-0d0c252ecfc5">
<img width="1680" alt="image" src="https://github.com/arix2000/LibraryWebApplication/assets/110868938/53820d26-4c76-4572-ac18-67fb17ff939e">

Jakoś bym rozdzielił wizualnie globalna historie od historii użytkownika. Zrobić je np w formie kart, z marginesami przy bocznych krawędziach strony. Z innym odcieniem tła, gdzie tytuły byłyby w formie headera "przyklejonego" do karty (coś jak masz w homepage). No i kiedy brak jakiejkolwiek historii, to trzeba wyśrodkować względem "środka połowy strony" zarówno te hedery, jak i obrazki :)
pozdro600

2023-06-06 23:36 UTC, joohnnyvv requested changes
<img width="746" alt="Zrzut ekranu 2023-06-7 o 01 32 12" src="https://github.com/arix2000/LibraryWebApplication/assets/110868938/a6ca4cac-bdc3-4561-9b19-0c4a5b3dab6f">

No i tu ten radius na zdjeciu mi sie nie klei trochę, można by tez rozdzielić jakaś szara kreska te szczegóły od tych informacji widocznych przed kliknięciem. Taka np nie na cala szerokość tylko tak wiesz, elegancka wyśrodkowana z marginesem po bokach z 20% :)

2023-06-06 23:42 UTC, joohnnyvv commented
<img width="1680" alt="image" src="https://github.com/arix2000/LibraryWebApplication/assets/110868938/914b50bd-20fc-4b0b-9b17-7ff49f51c6b9">

Sorry Arek, ale ten header to juz chyba serio na odpierdol zrobiłeś specjalnie XD

2023-06-06 23:44 UTC, joohnnyvv commented
Ogólnie trzeba będzie tez przy tych stójkowych userach usunąć im wszystkie książki które niby maja wypożyczone/zarezerwowane, bo to komicznie wyglada jak się logujesz, wchodzisz na home page i widzisz ze ma kilka zarezerwowanych/wypożyczonych, a w historii pustki

2023-06-07 10:24 UTC, joohnnyvv commented
<img width="1680" alt="image" src="https://github.com/arix2000/LibraryWebApplication/assets/110868938/219f8ea9-b92b-4638-8b50-04a1e7044b4c">
Pusta strona na mniejszym wyswietlaczu wyglada tez słabo bo jeszcze bardziej do boków się przesuwają te elementy

2023-06-07 22:51 UTC, joohnnyvv commented
![obraz](https://github.com/arix2000/LibraryWebApplication/assets/110868938/38f6f6b1-9ba0-4939-9ccf-6b9e8ee04589)
Ze spraw kosmetycznych troche bym padding zwiekszyl kiedy nie ma zadnej historii, bo tekst praktycznie nachodzi na granice tego jasniejszego tła

2023-06-07 22:53 UTC, joohnnyvv commented
![obraz](https://github.com/arix2000/LibraryWebApplication/assets/110868938/24c14c32-1785-48f6-b597-e1ef79487757)
Nadal ten border radius mi nie siedzi w prawym gornym rogu okladki :/

2023-06-07 23:02 UTC, joohnnyvv requested changes
No w sumie to ta kosmetyka została imo

2023-06-08 09:20 UTC, arix2000 commented
> ![obraz](https://user-images.githubusercontent.com/110868938/244219239-24c14c32-1785-48f6-b597-e1ef79487757.png) Nadal ten border radius mi nie siedzi w prawym gornym rogu okladki :/

Nie wiem co tutaj nie siedzi więc tego nie zmieniam, wygląda git dla mnie, nie mam pomysłu żeby to lepiej wyglądało więc tak bym to też zostawił

2023-06-09 15:15 UTC, joohnnyvv approved these changes
Jest w porząsiu

2023-06-09 16:34 UTC, merged