Lib 24 bug/feature book item limit borrow/return action to librarian
arix2000/LibraryWebApplication pull request #29
Opened 2023-06-22 13:27 UTC by joohnnyvv

https://www.youtube.com/watch?v=WHHGOYu6Fl0

2023-06-26 09:36 UTC, arix2000 commented
To nie powinno być **Lend a book**? 
![image](https://github.com/arix2000/LibraryWebApplication/assets/39887315/671fdc02-51bd-4a7b-a19b-b55df3a7c9b2)

2023-06-26 10:04 UTC, arix2000 commented
Ten reserve button to się chyba powinien w tej sytuacji do prawej przesunąć :D
![image](https://github.com/arix2000/LibraryWebApplication/assets/39887315/d9fc3cee-2f5d-4ace-a175-5ba3d55f942a)

2023-06-26 10:08 UTC, arix2000 requested changes
Prosze odesłać do kosmetycznki
A tak generalnie to git, jest coraz lepiej :dancing_men:

2023-06-26 10:08 UTC, arix2000 commented on src/components/BookSearch/BorrowBookModal.js
> +        console.log(user);
zapewne się zapodziało - do usunięcia

2023-06-26 10:08 UTC, arix2000 commented on src/components/BookSearch/BorrowBookModal.js
> +        const rowClass = isSelected ? styles.selectedRow : styles.usersTableRow;
`class` jest bardzo szeroko używane w programowaniu dlatego generalnie unikamy tego w nazwach czegokolwiek (sama nazwa `className` też nie była nigdy dobrym pomysłem ze strony html/css). Zamieńmy zatem `rowClass` może na `userRowStyles`

2023-06-26 10:08 UTC, arix2000 commented on src/components/BookSearch/BorrowBookModal.js
> +export default function BorrowBookModal({ show, onHide, book }) {
generalnie unikałbym dwóch komponentów w jednym pliku, szczególnie że ma on już 130 lini oddziel prosze te dwie funkcje do osobnych plików

2023-06-26 10:08 UTC, arix2000 commented on src/components/BookSearch/BorrowBookModal.js
> +  const [selectedUserId, setSelectedUserId] = useState(null);
puste `id` w programowaniu oznacza się zazwyczaj poprzez `-1`  w ten sposób pokazujemy że puste `id` to zamierzony efekt gdzie `null` raczej informuje o jakimś błędzie. Zostawiam to do twojej dyspozycji, jak chcesz to zmień jak nie to zostaw.

2023-06-26 10:08 UTC, arix2000 commented on src/components/BookSearch/BorrowBookModal.js
> +  const [isChecked, setIsChecked] = useState(false);
wydaje mi się że nie potrzebujesz tego state więcej info poniżej

2023-06-26 10:08 UTC, arix2000 commented on src/components/BookSearch/BorrowBookModal.js
> +          disabled={!isChecked}
możesz to równie dobrze sprawdzić bez dodatkowej zmiennej za pomocą `!selectedUserId` - co zwraca true jeżeli `selectedUserId` nie jest puste albo null albo unsiggned itp. Jeżeli się zdecydujesz na defaultową wartość `-1` to wystarczy tu zrobić `selectedUserId < 0`

2023-06-26 10:08 UTC, arix2000 commented on src/components/BookSearch/BorrowBookModal.js
> +      onClick={(e) => {
Nie potrzebujesz tego onClick, wystarczy że w obsłudze kliknięcia w userRow dasz `stopPropagation` (albo `preventDefault` bo juz nie pamiętam dokładnie)

2023-06-26 10:08 UTC, arix2000 commented on src/components/BookSearch/BorrowBookModal.js
> +  const handleClick = (userId) => {
Ogólna nazwa bardzo, zmieńmy na coś typu `onUserClicked` albo `handleUserClick`

2023-06-26 10:08 UTC, arix2000 commented on src/components/BookSearch/BorrowBookModal.js
> +            <UserRow
w sumie to nie jest `UserRow` tak naprawde to jest `UserTable` dobrze myśle? jak tak to pozmieniaj nazwy

2023-06-26 10:08 UTC, arix2000 commented on src/components/BookSearch/common/BorrowButton.js
> +    // setIsBookBorrowed(true);
zakomentowany kod to największy prześladowca programistycznej ludzkości, unikaj jak ognia, wiem z doświadczenia że potem tego się prawie nie da usunąć, więc póki wiemy  że to nie potrzebne, usuń to tak samo z tym poniżej

2023-06-26 10:17 UTC, joohnnyvv commented
> To nie powinno być **Lend a book**? 
> 
> ![image](https://github.com/arix2000/LibraryWebApplication/assets/39887315/671fdc02-51bd-4a7b-a19b-b55df3a7c9b2)
> 
> 

Tej napisałem ze to poprawie po czym tego nie zrobiłem, sory xd

2023-06-26 23:46 UTC, joohnnyvv commented on src/components/BookSearch/BorrowBookModal.js
> +      onClick={(e) => {
Potrzebuje bo jak zrobię tak jak mówisz to mi sie klikają komponenty będące "poniżej". Z początku zrobiłem tak jak mówisz i nie znalazłem lepszego rozwiązania na to. Nawet jak na rów kliknąłem to było to samo lol xd

2023-06-27 21:10 UTC, arix2000 requested changes
Good, three more changes

2023-06-27 21:10 UTC, arix2000 commented on src/components/BookSearch/BorrowBookModal.js
> +            <UserTableRow
To lista elementów <tr> co czyni z tego nic innego jak tabele po prostu, i chyba bym to dał w liczbie mnogiej `UsersTable` albo `UserTable` jak wolisz.

2023-06-28 11:02 UTC, arix2000 reviewed
Ok chyba musiałem to zaakceptować żebyś zobaczył

2023-06-28 11:02 UTC, arix2000 commented on src/components/BookSearch/BookItem.js
> +    if (loggedUser.role === "librarian") {
string `"librarian"` zamień na enum `RolesEnum.librarian` żeby wszystkie te role z jednego miejsca były używane

2023-06-28 11:02 UTC, arix2000 commented on src/components/BookSearch/BookItem.js
> +              <BorrowButton rowStyles={styles.itemButtonSection} book={book} isLibrarian={isLibrarian}/>
Możesz usunąć praktycznie wszystko u góry dotyczące zmiennej `isLibrarian` i zamiast niej używać tylko `loggedUser.role === RolesEnum.librarian` i będzie tak samo tylko prościej i mniej kodu

2023-06-28 12:47 UTC, arix2000 approved these changes
Bardzo ładnie, bardzo mi się podoba
https://www.youtube.com/watch?v=BIRp5XKFM_g

2023-06-29 18:10 UTC, merged