Lib 02
arix2000/LibraryWebApplication pull request #3
Opened 2023-03-13 13:48 UTC by jrembikowski

2023-03-14 19:01 UTC, arix2000 commented
1. Lista książek wygląda troche jak z lat 90 nie uważasz? zamieńmy to może na jakieś kafelki czy coś w tym stylu?
2. ładujesz wszyskie książki w tym samym momencie w ten sposób zapychana jest cała pamięć a aplikacja dostaje ścinki (widać przy zmienianiu wielkości okna). Nie możesz generować wszystkich elementów na raz, musisz użyć jakiejś listy która będzie dbała o ładowanie tylko elementów widocznych na ekranie jeżeli to nie pomoże (strona nadal będzie się ładować długo) to użyj paginacji
Tutaj jest wtyczka która powinna ci pomóc: https://github.com/beforesemicolon/flatlist-react
Jeżeli ta będzie średnia to znalazłem jeszcze coś takiego: https://github.com/Flipkart/recyclerlistview

NavBar jest chyba nieco zbyt jasny a ta ikona "X" ma niepotrzebny gradient i kolor, lepiej żeby ta ikona była biała jak text

![image](https://user-images.githubusercontent.com/39887315/225109472-79844294-c184-46ee-8372-5bf97092071a.png)

2023-03-14 19:03 UTC, arix2000 commented on package.json
> +    "json-loader": "^0.5.7"
Niewidze żeby to było gdzieś użyte, możemy to usunąć co nie?

2023-03-14 19:17 UTC, arix2000 requested changes

2023-03-14 19:17 UTC, arix2000 commented on package.json
> +    "json-loader": "^0.5.7"
Niewidze żeby to było gdzieś użyte, możemy to usunąć co nie?

2023-03-14 19:17 UTC, arix2000 commented on src/App.js
> +    const handleSearchSubmit = (term) => {
`term` brzmi co najmniej dziwnie, może zmieńmy tą nazwe na `query`?

2023-03-14 19:17 UTC, arix2000 commented on src/App.js
> +            <BookList books={books}/>
Nie musisz przesyłać listy książek tutaj, możesz ją zaimportować prosto do pliku gdzie jest komponent BookList

2023-03-14 19:17 UTC, arix2000 commented on src/components/AdminPanel.js
> +      <div>
skąd te zmiany? jak ich nie widziałeś to możliwe że twój branch nie jest aktualny z master'em

2023-03-14 19:17 UTC, arix2000 commented on src/components/BookSearch/BookList.js
> +            <a href="#">
co to daje?

2023-03-14 19:17 UTC, arix2000 commented on src/components/BookSearch/BookList.js
> +                    className=""
to chyba jest useless

2023-03-15 00:00 UTC, jrembikowski commented on src/components/BookSearch/BookList.js
> +                    className=""
nie jest, nie zdazylem dodac, a tam bd customowy css

2023-03-15 00:04 UTC, jrembikowski commented on src/App.js
> +    const handleSearchSubmit = (term) => {
ok

2023-03-15 00:06 UTC, jrembikowski commented on src/App.js
> +            <BookList books={books}/>
Ale po co skoro z app.js bedzie mozna do wszedzie przekazac gdzie potrzeba, a nie importowac wszedzie z osobna

2023-03-16 12:39 UTC, closed without merging