Logic for login
arix2000/LibraryWebApplication pull request #8
Opened 2023-03-28 23:11 UTC by maciekkielducki

<3

2023-03-29 12:33 UTC, jrembikowski commented
<img width="484" alt="image" src="https://user-images.githubusercontent.com/110868938/228536278-733ec381-afd0-46a2-9ecd-9b3348eec053.png">
Jak na moje git, mógłbyś tylko poprawić jeden label - wprowadzamy login a nie e-mail, a label jest Email adress (a jeśli będziemy maile dodawać to i tak bym poprawił bo powinno być przez dwa "d" - "Email address")

2023-03-30 21:05 UTC, arix2000 commented
Wydaje mi się że stary layout login page troche odbiega od tego co mamy teraz

<div>
    <table>
	    <tr>
    	    <td>
        	    <img src="https://user-images.githubusercontent.com/39887315/228961255-83fcddaa-b7a4-454a-b614-a40a8fc4cd9b.png" width="400"/>
      	    </td>
            <td>
            	<img src="https://user-images.githubusercontent.com/39887315/228961862-54dafbd5-774d-44a8-87bd-f46cd8ef4a27.png" width="400"/>
            </td>
        </tr>
    </table>
</div>

Dodałbym zaokrąglenia większe (tak jak po lewej) oraz text field taki jak po prawej bo wydaje mi się że nieco łagodniej dla oka wygląda przez mniejszy skok kolorów wszystkie style do tego co po prawej są w `styles/admin-panel-styles.css`. 
Możesz wgl przekopiować to pole z odkrywanym hasłem bo na loginie też to powinno być.

2023-03-30 21:10 UTC, arix2000 commented
![image](https://user-images.githubusercontent.com/39887315/228965188-697cc46d-5e21-46fa-9ba1-2795305280b5.png)

Btw. ten napis jest useless chyba bo nie mamy w planach robić odzyskiwania hasła co nie?

2023-03-30 21:40 UTC, arix2000 commented
![image](https://user-images.githubusercontent.com/39887315/228970633-376a186b-cb93-4af9-89a4-80d4218348cc.png)
To info że zalogowano raczej nie będzie potrzebne bo po zalogowaniu od razu polecimy do następnej strony i po tym user ogarnie że się zalogował

2023-03-30 21:43 UTC, arix2000 commented
Nie zapomnij rozwiązać konfliktów :sunglasses:

2023-03-30 21:44 UTC, arix2000 requested changes

2023-03-30 21:44 UTC, arix2000 commented on src/components/LoginPage/LoginPage.js
> +    const user = users.find((u) => u.login === login && u.password === password);
1. zmiana nazwy by się tu przydała jako że to jest boolean np. `isLoginSuccess`
2. 13 i 14 linia może być zamieniona w jedną:
`const isLoginSuccess = userManager.getUsers().find((u) => u.login === login && u.password === password);`

2023-03-30 21:44 UTC, arix2000 commented on src/components/LoginPage/LoginPage.js
> +    }
ten `if - else` może zostać zastąpiony przez lambda expression: `setMessage(user ? 'Zalogowano!' : 'Nieprawidłowy email lub hasło');`

2023-03-30 21:44 UTC, arix2000 commented on src/App.js
> +            {/* <AdminPanel /> */}
Myśle że możemy to usunąć, jak będe robić nawigacje to to ogarne już na własną ręke

2023-03-30 21:44 UTC, arix2000 commented on src/components/admin_panel/dialogs/AddEditUserDialog.jsx
Ten plik do przywrócenia chyba bo nie mamy emaili tylko loginy, myśle też że tak będzie prościej

2023-03-31 08:11 UTC, joohnnyvv commented on src/components/LoginPage/LoginPage.js
> +    }
W sumie srac na ten warunek skoro i tak nie potrzebujemy info ze zalogowano

2023-04-04 22:05 UTC, joohnnyvv commented on src/components/LoginPage/LoginPage.js
>      <div className="background-color">
W 16 i 17 linii masz dwa takie same divy - jednego możesz wyrzucić

2023-04-06 19:00 UTC, arix2000 approved these changes
Nice!

2023-04-06 19:06 UTC, merged